version: '3'

services:
  disperse1:
    image: disperse
    ports:
    - 8081:8080
  disperse2:
    image: disperse
    ports:
    - 8082:8080
  disperse3:
    image: disperse
    ports:
    - 8083:8080
  nginx:
    image: nginx:1.17.2-alpine
    ports:
    - 80:80
    - 443:443
    volumes:
    - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - disperse1
    - disperse2
    - disperse3
